In [28]:
import numpy as np
import pandas as pd

In [29]:
df = pd.read_csv(r"..\Numpy\music.csv")
df

           Artist Genres  Listeners     Plays
0  Billie Holiday   Jazz    1300000  27000000
1    Jimi Hendrix   Rock    2700000  70000000
2     Miles Davis   Jazz    1500000  48000000
3             SIA    Pop    2000000  74000000

In [30]:
df.groupby('Genres')
df.groupby('Genres')['Listeners'].mean()

Genres
Jazz    1400000.0
Pop     2000000.0
Rock    2700000.0
Name: Listeners, dtype: float64

In [31]:
df.groupby('Genres')['Plays'].sum()

Genres
Jazz    75000000
Pop     74000000
Rock    70000000
Name: Plays, dtype: int64

In [32]:
df.groupby('Genres')['Artist'].count()

Genres
Jazz    2
Pop     1
Rock    1
Name: Artist, dtype: int64

In [33]:
df.groupby('Genres').size() # gives freq of genres - counts also if there are missing values in artists

Genres
Jazz    2
Pop     1
Rock    1
dtype: int64

In [34]:
df.groupby('Genres')['Listeners'].max()
df.groupby('Genres')['Listeners'].min()

Genres
Jazz    1300000
Pop     2000000
Rock    2700000
Name: Listeners, dtype: int64

In [35]:
df.groupby('Genres')['Listeners'].agg(["mean",'max','min'])

             mean      max      min
Genres
Jazz    1400000.0  1500000  1300000
Pop     2000000.0  2000000  2000000
Rock    2700000.0  2700000  2700000

In [36]:
df.groupby('Genres').agg({
    'Listeners' : ['mean', 'max'],
    'Plays' : 'sum'
})

        Listeners              Plays
             mean      max       sum
Genres
Jazz    1400000.0  1500000  75000000
Pop     2000000.0  2000000  74000000
Rock    2700000.0  2700000  70000000

In [37]:
df.groupby(['Genres','Artist'])['Listeners'].mean()

Genres  Artist
Jazz    Billie Holiday    1300000.0
        Miles Davis       1500000.0
Pop     SIA               2000000.0
Rock    Jimi Hendrix      2700000.0
Name: Listeners, dtype: float64

In [41]:
# reset index
result = df.groupby('Genres')['Listeners'].sum()
result
result = result.reset_index()
result

  Genres  Listeners
0   Jazz    2800000
1    Pop    2000000
2   Rock    2700000

In [51]:
df.groupby('Genres')['Listeners'].mean().sort_values(ascending = False)

Genres
Rock    2700000.0
Pop     2000000.0
Jazz    1400000.0
Name: Listeners, dtype: float64

In [46]:
genrePlays = df.groupby('Genres')['Plays'].sum()
genrePlays[genrePlays>70_000_000]

Genres
Jazz    75000000
Pop     74000000
Name: Plays, dtype: int64