In [196]:
import pandas as pd
import numpy as np

In [197]:
# ====SERIES====
# from nd array
s = pd.Series(np.random.randn(5),index = ['A','B','C','D','E'], name="Learning Series")
s
# s.index
# pd.Series(np.random.randn(5))
# pd.Series([1,2,3,4,5])
# pd.Series(1,2,3,4,5) ------ error

A   -0.683118
B   -0.652366
C   -0.035103
D   -1.025821
E   -1.766244
Name: Learning Series, dtype: float64

In [198]:
# from dict
dictionary = {'b':1, 'a':2, 'c':0}
d = pd.Series(dictionary)
# d
pd.Series(dictionary,index = ['a','b','c','d','e'])

a    2.0
b    1.0
c    0.0
d    NaN
e    NaN
dtype: float64

In [199]:
# from dict
dictionary = {'b':1, 'b':2, 'c':0} # overwrite
d = pd.Series(dictionary)
d

b    2
c    0
dtype: int64

In [200]:
# from scalar value
pd.Series(5,index = ['a','b','c','d','e'])

s.iloc[0]
s.iloc[:3]
s[s > s.median()]
s.iloc[[1,2,4]]
np.exp(s) # e^x
s.array
s.to_numpy()
'E' in s
'F' in s
# s['f'] ----- exception raised
s.get('f') # ---- no exception raised
s.get('f',np.nan)

nan

In [201]:
# vectorised ops and label alignment
s + s
s*2
np.exp(s)
s.iloc[1:] + s.iloc[:-1]
s.name
s=s.rename("Learned Series")
s**2

A    0.466650
B    0.425581
C    0.001232
D    1.052308
E    3.119619
Name: Learned Series, dtype: float64

In [202]:
# ====DATA FRAME====
# from dict of series
d = {
    'one': pd.Series([1,2,3.0], index = ['a','b','c']),
    'two': pd.Series([4.0,5,6,1], index = ['a','b','c','d'])
}
df = pd.DataFrame(d)
df
pd.DataFrame(d,index = ['b','d','a'])
pd.DataFrame(d,index=['a','b','e'],columns = ['two','three'])
# df.index
# df.columns

   two three
a  4.0   NaN
b  5.0   NaN
e  NaN   NaN

In [203]:
# dict of ndarrays/lists
d = {
    'one': [1,2,3,4], # arrays length different = ValueError
    'two': [2,3,4,5]
}
pd.DataFrame(d)
pd.DataFrame(d, index = ['a','b','c','d']) # index length not same = ValueError

   one  two
a    1    2
b    2    3
c    3    4
d    4    5

In [204]:
# from structured or record array
data = np.zeros((2,), dtype = [('A','i4'),('B','f4'),('C','S10')])
data[:] = [(1,2.0,"Hello"),(2,4.0,"World")]
pd.DataFrame(data, index=['one','two'], columns=['B','C','A'])

       B         C  A
one  2.0  b'Hello'  1
two  4.0  b'World'  2

In [205]:
# from a list of dicts
data2 = [{'a':1, 'b':2,'c':1},{'c':1,'d':3,'a':2}]
pd.DataFrame(data2, index=['first','second'],columns=['b','c','d','a'])

          b  c    d  a
first   2.0  1  NaN  1
second  NaN  1  3.0  2

In [206]:
# column selection, addition, deletion
df['one']
df['three'] = df['one']*df['two']
df['flag'] = df['one']>=2
del df['two']
df

   one  three   flag
a  1.0    4.0  False
b  2.0   10.0   True
c  3.0   18.0   True
d  NaN    NaN  False

In [207]:
df.pop('three') # in fact we can store popped value x = df.pop('three')
df

   one   flag
a  1.0  False
b  2.0   True
c  3.0   True
d  NaN  False

In [208]:
df['new'] = 'another col'
df

   one   flag          new
a  1.0  False  another col
b  2.0   True  another col
c  3.0   True  another col
d  NaN  False  another col

In [209]:
df['truncated_one'] = df['one'][:2]
df

   one   flag          new  truncated_one
a  1.0  False  another col            1.0
b  2.0   True  another col            2.0
c  3.0   True  another col            NaN
d  NaN  False  another col            NaN

In [210]:
# df.insert(loc,column,value)
df.insert(2,'bar',df['one'])
df

   one   flag  bar          new  truncated_one
a  1.0  False  1.0  another col            1.0
b  2.0   True  2.0  another col            2.0
c  3.0   True  3.0  another col            NaN
d  NaN  False  NaN  another col            NaN

In [211]:
df.insert(4,'new_col',[5,5,5,9])
df

   one   flag  bar          new  new_col  truncated_one
a  1.0  False  1.0  another col        5            1.0
b  2.0   True  2.0  another col        5            2.0
c  3.0   True  3.0  another col        5            NaN
d  NaN  False  NaN  another col        9            NaN

In [212]:
# drop col
df_new = df.drop('new',axis=1)
df_new
# drop row
df_new = df.drop('b',axis=0)
df_new

   one   flag  bar          new  new_col  truncated_one
a  1.0  False  1.0  another col        5            1.0
c  3.0   True  3.0  another col        5            NaN
d  NaN  False  NaN  another col        9            NaN

In [213]:
# INDEXING & SELECTION
# Select column
df['one']
df.one
type(df.one)
# select row by label
df.loc['a']
# select row by integer location
df.iloc[0] # df.iloc['a'] gives error
type(df.iloc[0])
# slice rows
df[1:3]
# select rows by bool vector
df[df['one']<=2]
df.one.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [230]:
# data alignment & arithmetic
my_data_frame = pd.DataFrame(np.random.randint(1,5, size=(6,4)),columns = ['A','B','C','D'])
df2 = pd.DataFrame(np.random.randint(0,8, size=(4,3)), columns=['A','B','C'])
my_data_frame + df2
print(my_data_frame)
print(my_data_frame.iloc[0])
print(my_data_frame-my_data_frame.iloc[0])
# print(my_data_frame*5+2)
# print(1/my_data_frame)
print(my_data_frame**4)

   A  B  C  D
0  2  3  2  1
1  3  4  2  2
2  3  2  1  1
3  4  1  3  2
4  2  2  1  1
5  2  1  2  3
A    2
B    3
C    2
D    1
Name: 0, dtype: int32
   A  B  C  D
0  0  0  0  0
1  1  1  0  1
2  1 -1 -1  0
3  2 -2  1  1
4  0 -1 -1  0
5  0 -2  0  2
     A    B   C   D
0   16   81  16   1
1   81  256  16  16
2   81   16   1   1
3  256    1  81  16
4   16   16   1   1
5   16    1  16  81

In [231]:
# boolean ops
df1 = pd.DataFrame({'a':[1,0,1],'b':[0,1,1]},dtype=bool)
df2 = pd.DataFrame({'a':[0,1,1],'b':[1,1,0]},dtype=bool)
df1 & df2

       a      b
0  False  False
1  False   True
2   True  False

In [ ]:
# numpy functions usable
np.exp(df1)
np.asarray(df1) # dtype = bool

array([[ True, False],
       [False,  True],
       [ True,  True]])