In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r"..\NumPy\music.csv")
df

           Artist Genres  Listeners        Plays
0  Billie Holiday   Jazz  13,00,000  2,70,00,000
1    Jimi Hendrix   Rock  27,00,000  7,00,00,000
2     Miles Davis   Jazz  15,00,000  4,80,00,000
3             SIA    Pop  20,00,000  7,40,00,000

In [ ]:
df.dtypes
df['Plays']
df[['Plays']]

         Plays
0  2,70,00,000
1  7,00,00,000
2  4,80,00,000
3  7,40,00,000

In [18]:
df[['Artist','Plays']]

           Artist        Plays
0  Billie Holiday  2,70,00,000
1    Jimi Hendrix  7,00,00,000
2     Miles Davis  4,80,00,000
3             SIA  7,40,00,000

In [ ]:
df.iloc[2].dtypes # df.iloc[2].dtype also works

In [41]:
df.iloc[1,3]
df.loc[3,['Artist','Plays']]
df['Listeners']>'15,00,000'
df[(df['Listeners']>'15,00,000') & ~(df['Artist']=='SIA')]
df[(df['Listeners']>'15,00,000') | ~(df['Artist']!='SIA')]
df.loc[(df['Listeners']>'15,00,000'), ['Artist','Plays']] = "Something fishy"
df

            Artist Genres  Listeners            Plays
0   Billie Holiday   Jazz  13,00,000      2,70,00,000
1  Something fishy   Rock  27,00,000  Something fishy
2      Miles Davis   Jazz  15,00,000      4,80,00,000
3  Something fishy    Pop  20,00,000  Something fishy