In [68]:
import pandas as pd
import numpy as np

In [69]:
df = pd.read_csv(r"..\NumPy\music.csv")
df_copy = df.copy()
df

           Artist Genres  Listeners     Plays
0  Billie Holiday   Jazz    1300000  27000000
1    Jimi Hendrix   Rock    2700000  70000000
2     Miles Davis   Jazz    1500000  48000000
3             SIA    Pop    2000000  74000000

In [70]:
df.dtypes
df['Plays']
df[['Plays']]

      Plays
0  27000000
1  70000000
2  48000000
3  74000000

In [71]:
df[['Artist','Plays']]

           Artist     Plays
0  Billie Holiday  27000000
1    Jimi Hendrix  70000000
2     Miles Davis  48000000
3             SIA  74000000

In [72]:
df.iloc[2].dtypes # df.iloc[2].dtype also works

dtype('O')

In [73]:
df.iloc[1,3]
df.loc[3,['Artist','Plays']]
df['Listeners']>1500000
df[(df['Listeners']>1500000) & ~(df['Artist']=='SIA')]
df[(df['Listeners']>1500000) | ~(df['Artist']!='SIA')]
# df.loc[(df['Listeners']>1500000), ['Artist','Plays']] = "Something fishy"
# df

         Artist Genres  Listeners     Plays
1  Jimi Hendrix   Rock    2700000  70000000
3           SIA    Pop    2000000  74000000

In [74]:
df['PlaysPerListener'] = df['Plays']/df['Listeners']
df['Platform'] = 'Spotify'
df['Rank'] = [3,2,4,1] # list must contain same no. of elements as rows - ValueError
# modifyung existing col
df['Rank'] = df['Rank']*10
df.loc[df['Artist']=='SIA','Genres'] = 'Electro-Pop'
df['Popular'] = df['Listeners']>=2000000
df['Popularity'] = np.where(df['Listeners']>=2000000,"High","Normal")
# Renaming columns
df = df.rename(columns = {'Plays':'Total Plays', 'Artist':'Artist Name'})
# drop a column
df = df.drop(columns = ['Popular','Platform'])
# removing rows
df = df.drop(index=2)
df

,Artist Name,Genres,Listeners,Total Plays,PlaysPerListener,Rank,Popularity
0,Billie Holiday,Jazz,1300000,27000000,20.769231,30,Normal
1,Jimi Hendrix,Rock,2700000,70000000,25.925926,20,High
3,SIA,Electro-Pop,2000000,74000000,37.000000,10,High

In [75]:
# BASIC ANALYSIS & STATISTICS
df.describe()

       Listeners   Total Plays  PlaysPerListener  Rank
count        3.0  3.000000e+00          3.000000   3.0
mean   2000000.0  5.700000e+07         27.898386  20.0
std     700000.0  2.605763e+07          8.293215  10.0
min    1300000.0  2.700000e+07         20.769231  10.0
25%    1650000.0  4.850000e+07         23.347578  15.0
50%    2000000.0  7.000000e+07         25.925926  20.0
75%    2350000.0  7.200000e+07         31.462963  25.0
max    2700000.0  7.400000e+07         37.000000  30.0

In [76]:
df['Listeners'].describe()
df['PlaysPerListener'].mean()
# df.mean() - TypeError
df['Total Plays'].sum()
df['Listeners'].min()
df['Listeners'].max()
df['Listeners'].median()
df['Total Plays'].std()
df['Listeners'].count() # gives no. of all non missing values irrespective of whether they are unique or not
df['Genres'].value_counts()
df['Genres'].unique() # All unique existing genres
df['Genres'].nunique() # Tells no. of all unique genres
df.mean(numeric_only=True)
df.sum(numeric_only=True)
df[df['Total Plays']== df['Total Plays'].max()]
(df['Listeners']>2_000_000).sum() # sums bool values True = 1, False = 0
df['Total Plays'].idxmax() # index of the row with max plays
df['Total Plays'].idxmin() # index of row with min plays
df.loc[df['Total Plays'].idxmax()]
df.loc[df['Total Plays'].idxmin(),'Artist Name']

'Billie Holiday'

In [77]:
# SORTING
df.sort_values('Listeners')
df.sort_values('Listeners',ascending = False) # df not modified
df.sort_values(['Genres','Rank'],ascending = [True,False]) # priority -> Genres then Rank
# Sorting by a series
df['Total Plays'].sort_values()
df.sort_index() # sorts by index number
# top 2 artists by number of plays
df.sort_values('Total Plays',ascending=False).head(2)
df.sort_values('Total Plays',ascending=False).head(2)['Artist Name']
# sorting + filtering
df[df['Genres']=='Jazz'].sort_values('Total Plays',ascending = False)

,Artist Name,Genres,Listeners,Total Plays,PlaysPerListener,Rank,Popularity
0,Billie Holiday,Jazz,1300000,27000000,20.769231,30,Normal

In [78]:
# FUNCTIONS & VECTORISED OPS

# String func
# df['Artist'].upper() ❌ - it is a series not a single string
df['Artist Name'].str.upper()
df['Artist Name'].str.lower()
df['Artist Name'].str.len()
# df['Artist Name'].str.contains('i', case = False)
df['Artist Name'].str.contains('i')
df[df['Artist Name'].str.contains('i')]

,Artist Name,Genres,Listeners,Total Plays,PlaysPerListener,Rank,Popularity
0,Billie Holiday,Jazz,1300000,27000000,20.769231,30,Normal
1,Jimi Hendrix,Rock,2700000,70000000,25.925926,20,High

In [79]:
# apply()
def classify_plays(x) :
    if x > 50_000_000 :
        return "High"
    return "Low"

df['PlayCategory'] = df['Total Plays'].apply(classify_plays)
df['PlayCat'] = df['Total Plays'].apply(lambda x: "High" if x > 50_000_000 else "Low")
df

,Artist Name,Genres,Listeners,Total Plays,PlaysPerListener,Rank,Popularity,PlayCategory,PlayCat
0,Billie Holiday,Jazz,1300000,27000000,20.769231,30,Normal,Low,Low
1,Jimi Hendrix,Rock,2700000,70000000,25.925926,20,High,High,High
3,SIA,Electro-Pop,2000000,74000000,37.000000,10,High,High,High

In [80]:
# map()
genre_map = {
    'Jazz' : 'J',
    'Rock' : 'R',
    'Pop' : 'P',
    # 'Electro-Pop' : 'E'
}
df['GenreCode'] = df['Genres'].map(genre_map)
# df['GenreCode'] = df['Genres'].map({'Jazz':'J','Rock':'R', 'Electro-Pop':'E'})
df
# df['Plays'].map(lambda x : x/1_000_000)

,Artist Name,Genres,Listeners,Total Plays,PlaysPerListener,Rank,Popularity,PlayCategory,PlayCat,GenreCode
0,Billie Holiday,Jazz,1300000,27000000,20.769231,30,Normal,Low,Low,J
1,Jimi Hendrix,Rock,2700000,70000000,25.925926,20,High,High,High,R
3,SIA,Electro-Pop,2000000,74000000,37.000000,10,High,High,High,NaN

In [81]:
df_copy.loc[2,'Genres'] = None
df_copy.loc[1, 'Listeners'] = None
df_copy.loc[2,'Plays'] = None
df_copy

           Artist Genres  Listeners       Plays
0  Billie Holiday   Jazz  1300000.0  27000000.0
1    Jimi Hendrix   Rock        NaN  70000000.0
2     Miles Davis    NaN  1500000.0         NaN
3             SIA    Pop  2000000.0  74000000.0

In [82]:
df_copy.isna()
df_copy.isnull()
df_copy.isna().sum() # per column
df_copy.isna().sum().sum() # entire data frame

np.int64(3)

In [83]:
df_copy[df_copy['Listeners'].isna()]

         Artist Genres  Listeners       Plays
1  Jimi Hendrix   Rock        NaN  70000000.0

In [84]:
df_copy[df_copy['Listeners'].notna()]

           Artist Genres  Listeners       Plays
0  Billie Holiday   Jazz  1300000.0  27000000.0
2     Miles Davis    NaN  1500000.0         NaN
3             SIA    Pop  2000000.0  74000000.0

In [85]:
df_copy.dropna() # doesn't modify the df_copy itself.

           Artist Genres  Listeners       Plays
0  Billie Holiday   Jazz  1300000.0  27000000.0
3             SIA    Pop  2000000.0  74000000.0

In [86]:
df_copy.dropna(subset = ['Listeners'])

           Artist Genres  Listeners       Plays
0  Billie Holiday   Jazz  1300000.0  27000000.0
2     Miles Davis    NaN  1500000.0         NaN
3             SIA    Pop  2000000.0  74000000.0

In [87]:
df_copy['Listeners'] = df_copy['Listeners'].fillna('Unknown')
df_copy
df_copy.dtypes
# df_copy['Listeners'] = df_copy['Listeners']/1_000_000 - TypeError

Artist           str
Genres           str
Listeners     object
Plays        float64
dtype: object

In [88]:
df_copy.loc[1,'Listeners'] = None
df_copy['Listeners'] = df_copy['Listeners'].fillna(
    df['Listeners'].mean()
)
df_copy

           Artist Genres  Listeners       Plays
0  Billie Holiday   Jazz  1300000.0  27000000.0
1    Jimi Hendrix   Rock  2000000.0  70000000.0
2     Miles Davis    NaN  1500000.0         NaN
3             SIA    Pop  2000000.0  74000000.0

In [89]:
df_copy.loc[len(df_copy)] = {'Artist' : 'SIA', 'Genres': 'Pop', 'Listeners': 2_000_000.0, 'Plays': 74_000_000}
df_copy

           Artist Genres  Listeners       Plays
0  Billie Holiday   Jazz  1300000.0  27000000.0
1    Jimi Hendrix   Rock  2000000.0  70000000.0
2     Miles Davis    NaN  1500000.0         NaN
3             SIA    Pop  2000000.0  74000000.0
4             SIA    Pop  2000000.0  74000000.0

In [90]:
df_copy.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [91]:
df_copy.duplicated().sum()
df_copy[df_copy.duplicated()]
df_copy.drop_duplicates() # not modified yet - just shown

           Artist Genres  Listeners       Plays
0  Billie Holiday   Jazz  1300000.0  27000000.0
1    Jimi Hendrix   Rock  2000000.0  70000000.0
2     Miles Davis    NaN  1500000.0         NaN
3             SIA    Pop  2000000.0  74000000.0

In [92]:
df_copy.duplicated(subset = ['Artist'])
df_copy.drop_duplicates(keep = 'last')

           Artist Genres  Listeners       Plays
0  Billie Holiday   Jazz  1300000.0  27000000.0
1    Jimi Hendrix   Rock  2000000.0  70000000.0
2     Miles Davis    NaN  1500000.0         NaN
4             SIA    Pop  2000000.0  74000000.0

In [93]:
df_copy.duplicated(keep = False)

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [94]:
# DATA TYPES & TYPE CONVERSION
df_copy = df_copy.drop_duplicates()
df_copy.loc[2,'Genres'] = 'Jazz'
df_copy.loc[2,'Plays'] = 48_000_000
df_copy

           Artist Genres  Listeners       Plays
0  Billie Holiday   Jazz  1300000.0  27000000.0
1    Jimi Hendrix   Rock  2000000.0  70000000.0
2     Miles Davis   Jazz  1500000.0  48000000.0
3             SIA    Pop  2000000.0  74000000.0

In [100]:
df_copy.dtypes
df_copy['Artist'].dtype
df_copy['Listeners'] = df_copy['Listeners'].astype(int)
df_copy['Listeners'].dtype

dtype('int64')

In [102]:
# nullable integers
my_series = pd.Series([1,2,3,4,None])
my_series.dtype

dtype('float64')

In [104]:
my_series.astype('Int64')

0       1
1       2
2       3
3       4
4    <NA>
dtype: Int64

In [108]:
df_copy['Listeners'] = pd.to_numeric(
    df['Listeners'],
    errors = 'coerce'
)
df_copy.dtypes

Artist           str
Genres           str
Listeners    float64
Plays        float64
dtype: object

In [109]:
df_copy['Genres'].astype('category').dtype

CategoricalDtype(categories=['Jazz', 'Pop', 'Rock'], ordered=False, categories_dtype=str)