In [13]:
import numpy as np
import pandas as pd

In [14]:
df = pd.read_csv(r"..\Numpy\music.csv")
df

           Artist Genres  Listeners     Plays
0  Billie Holiday   Jazz    1300000  27000000
1    Jimi Hendrix   Rock    2700000  70000000
2     Miles Davis   Jazz    1500000  48000000
3             SIA    Pop    2000000  74000000
4    Led Zeppelin   Rock    3000000  80000000
5    Taylor Swift    Pop    2500000  90000000

In [15]:
df.pivot_table(
    index = 'Genres',
    values = 'Listeners',
    aggfunc = 'mean'
)
# but this is same as df.groupby('Genres')['Listeners'].mean()

        Listeners
Genres
Jazz    1400000.0
Pop     2250000.0
Rock    2850000.0

In [16]:
sales = pd.DataFrame({
    "Month": ["Jan", "Jan", "Feb", "Feb", "Jan", "Feb"],
    "Region": ["India", "USA", "India", "USA", "India", "USA"],
    "Sales": [100, 200, 150, 250, 120, 300]
})
sales

  Month Region  Sales
0   Jan  India    100
1   Jan    USA    200
2   Feb  India    150
3   Feb    USA    250
4   Jan  India    120
5   Feb    USA    300

In [27]:
wide_sales = sales.pivot_table(
    index = 'Month',
    columns = 'Region',
    values = 'Sales',
    aggfunc = ['sum','mean']
)
wide_sales

         sum        mean
Region India  USA  India    USA
Month
Feb      150  550  150.0  275.0
Jan      220  200  110.0  200.0

In [24]:
sales.pivot(
    index = 'Month',
    columns = 'Region',
    values = 'Sales'
)
# ValueError - pivot cannot decide which value to take for multiple values. It has no aggfunc option

ValueError: Index contains duplicate entries, cannot reshape

In [21]:
df.pivot_table(
    index = 'Genres',
    values = ['Listeners','Plays'],
    aggfunc = 'mean'
)

        Listeners       Plays
Genres
Jazz    1400000.0  37500000.0
Pop     2250000.0  82000000.0
Rock    2850000.0  75000000.0

In [28]:
melted_sales = wide_sales.melt(ignore_index = False)
melted_sales

        NaN Region  value
Month
Feb     sum  India  150.0
Jan     sum  India  220.0
Feb     sum    USA  550.0
Jan     sum    USA  200.0
Feb    mean  India  150.0
Jan    mean  India  110.0
Feb    mean    USA  275.0
Jan    mean    USA  200.0

In [ ]:
wide_sales = sales.pivot_table(
    index = 'Month',
    columns = 'Region',
    values = 'Sales',
    aggfunc = 'sum',
    fill_value = 0
)
# fill_value fills missing data with 0 here
melted_sales = wide_sales.melt(ignore_index = False)
melted_sales

      Region  value
Month
Feb    India    150
Jan    India    220
Feb      USA    550
Jan      USA    200

In [ ]:
wide_sales = sales.pivot_table(
    index = 'Month',
    columns = 'Region',
    values = 'Sales',
    aggfunc = 'sum',
    fill_value = 0,
    margins = True
)
# margins give a grand total
wide_sales

Region  India  USA   All
Month
Feb       150  550   700
Jan       220  200   420
All       370  750  1120