In [1]:
import pandas as pd

In [2]:
sales = pd.DataFrame({
    'Day': [1,2,3,4,5],
    'Sales': [100,120,80,150,200]
})
sales

   Day  Sales
0    1    100
1    2    120
2    3     80
3    4    150
4    5    200

In [4]:
# Rolling average - average over x days out of all n days
sales['RollingAvg'] = sales['Sales'].rolling(3).mean()
# Nan, Nan, avg(day 1,2,3), avg(day 2,3,4), avg(day 3,4,5)
sales

   Day  Sales  RollingAvg
0    1    100         NaN
1    2    120         NaN
2    3     80  100.000000
3    4    150  116.666667
4    5    200  143.333333

In [5]:
sales['RollingSum'] = sales['Sales'].rolling(3).sum()
sales

   Day  Sales  RollingAvg  RollingSum
0    1    100         NaN         NaN
1    2    120         NaN         NaN
2    3     80  100.000000       300.0
3    4    150  116.666667       350.0
4    5    200  143.333333       430.0

In [9]:
sales['Sales'].cumsum()
sales['Sales'].cummin()
sales['Sales'].cummax()
sales['Sales'].cumprod()

0            100
1          12000
2         960000
3      144000000
4    28800000000
Name: Sales, dtype: int64

In [10]:
# expanding
# rolling means window slides
# expanding means kind of data increment - cummulation
sales['Sales'].expanding().mean()

0    100.0
1    110.0
2    100.0
3    112.5
4    130.0
Name: Sales, dtype: float64

In [13]:
# shift
sales['PreviousDaySales'] = sales['Sales'].shift(1)
sales

   Day  Sales  RollingAvg  RollingSum  PreviousDaySales
0    1    100         NaN         NaN               NaN
1    2    120         NaN         NaN             100.0
2    3     80  100.000000       300.0             120.0
3    4    150  116.666667       350.0              80.0
4    5    200  143.333333       430.0             150.0

In [14]:
sales['UpcomingSales'] = sales['Sales'].shift(-1)
sales

   Day  Sales  RollingAvg  RollingSum  PreviousDaySales  UpcomingSales
0    1    100         NaN         NaN               NaN          120.0
1    2    120         NaN         NaN             100.0           80.0
2    3     80  100.000000       300.0             120.0          150.0
3    4    150  116.666667       350.0              80.0          200.0
4    5    200  143.333333       430.0             150.0            NaN

In [15]:
sales['Change'] = sales['Sales'] - sales['Sales'].shift(1)
sales

   Day  Sales  RollingAvg  RollingSum  PreviousDaySales  UpcomingSales  Change
0    1    100         NaN         NaN               NaN          120.0     NaN
1    2    120         NaN         NaN             100.0           80.0    20.0
2    3     80  100.000000       300.0             120.0          150.0   -40.0
3    4    150  116.666667       350.0              80.0          200.0    70.0
4    5    200  143.333333       430.0             150.0            NaN    50.0

In [17]:
# percentage change
sales['Sales'].pct_change()*100

0          NaN
1    20.000000
2   -33.333333
3    87.500000
4    33.333333
Name: Sales, dtype: float64